// Curated Interview Roadmaps Data (Blind 75 & NeetCode 150)

export const CURATED_ROADMAPS = [
  {
    id: 'blind-75',
    title: 'Blind 75 Essential',
    description: 'The standard 75 LeetCode problems required for MAANG coding interviews.',
    problems: [
      {
        title: 'Two Sum',
        difficulty: 'Easy',
        category: 'Array & Hashing',
        url: 'https://leetcode.com/problems/two-sum/',
        platform: 'LeetCode',
        topics: ['Array', 'Hash Table'],
      },
      {
        title: 'Contains Duplicate',
        difficulty: 'Easy',
        category: 'Array & Hashing',
        url: 'https://leetcode.com/problems/contains-duplicate/',
        platform: 'LeetCode',
        topics: ['Array', 'Hash Table'],
      },
      {
        title: 'Valid Anagram',
        difficulty: 'Easy',
        category: 'Array & Hashing',
        url: 'https://leetcode.com/problems/valid-anagram/',
        platform: 'LeetCode',
        topics: ['String', 'Hash Table'],
      },
      {
        title: 'Group Anagrams',
        difficulty: 'Medium',
        category: 'Array & Hashing',
        url: 'https://leetcode.com/problems/group-anagrams/',
        platform: 'LeetCode',
        topics: ['Array', 'String', 'Hash Table'],
      },
      {
        title: 'Top K Frequent Elements',
        difficulty: 'Medium',
        category: 'Array & Hashing',
        url: 'https://leetcode.com/problems/top-k-frequent-elements/',
        platform: 'LeetCode',
        topics: ['Array', 'Hash Table', 'Heap/Priority Queue'],
      },
      {
        title: 'Product of Array Except Self',
        difficulty: 'Medium',
        category: 'Array & Hashing',
        url: 'https://leetcode.com/problems/product-of-array-except-self/',
        platform: 'LeetCode',
        topics: ['Array', 'Prefix Sum'],
      },
      {
        title: 'Valid Palindrome',
        difficulty: 'Easy',
        category: 'Two Pointers',
        url: 'https://leetcode.com/problems/valid-palindrome/',
        platform: 'LeetCode',
        topics: ['Two Pointers', 'String'],
      },
      {
        title: '3Sum',
        difficulty: 'Medium',
        category: 'Two Pointers',
        url: 'https://leetcode.com/problems/3sum/',
        platform: 'LeetCode',
        topics: ['Array', 'Two Pointers', 'Sorting'],
      },
      {
        title: 'Container With Most Water',
        difficulty: 'Medium',
        category: 'Two Pointers',
        url: 'https://leetcode.com/problems/container-with-most-water/',
        platform: 'LeetCode',
        topics: ['Array', 'Two Pointers', 'Greedy'],
      },
      {
        title: 'Best Time to Buy and Sell Stock',
        difficulty: 'Easy',
        category: 'Sliding Window',
        url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        platform: 'LeetCode',
        topics: ['Array', 'Dynamic Programming'],
      },
      {
        title: 'Longest Substring Without Repeating Characters',
        difficulty: 'Medium',
        category: 'Sliding Window',
        url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        platform: 'LeetCode',
        topics: ['Hash Table', 'String', 'Sliding Window'],
      },
      {
        title: 'Longest Repeating Character Replacement',
        difficulty: 'Medium',
        category: 'Sliding Window',
        url: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
        platform: 'LeetCode',
        topics: ['Hash Table', 'String', 'Sliding Window'],
      },
      {
        title: 'Valid Parentheses',
        difficulty: 'Easy',
        category: 'Stack',
        url: 'https://leetcode.com/problems/valid-parentheses/',
        platform: 'LeetCode',
        topics: ['String', 'Stack'],
      },
      {
        title: 'Find Minimum in Rotated Sorted Array',
        difficulty: 'Medium',
        category: 'Binary Search',
        url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        platform: 'LeetCode',
        topics: ['Array', 'Binary Search'],
      },
      {
        title: 'Search in Rotated Sorted Array',
        difficulty: 'Medium',
        category: 'Binary Search',
        url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        platform: 'LeetCode',
        topics: ['Array', 'Binary Search'],
      },
      {
        title: 'Reverse Linked List',
        difficulty: 'Easy',
        category: 'Linked List',
        url: 'https://leetcode.com/problems/reverse-linked-list/',
        platform: 'LeetCode',
        topics: ['Linked List'],
      },
      {
        title: 'Merge Two Sorted Lists',
        difficulty: 'Easy',
        category: 'Linked List',
        url: 'https://leetcode.com/problems/merge-two-sorted-lists/',
        platform: 'LeetCode',
        topics: ['Linked List'],
      },
      {
        title: 'Reorder List',
        difficulty: 'Medium',
        category: 'Linked List',
        url: 'https://leetcode.com/problems/reorder-list/',
        platform: 'LeetCode',
        topics: ['Linked List', 'Two Pointers'],
      },
      {
        title: 'Invert Binary Tree',
        difficulty: 'Easy',
        category: 'Trees',
        url: 'https://leetcode.com/problems/invert-binary-tree/',
        platform: 'LeetCode',
        topics: ['Tree', 'DFS', 'BFS'],
      },
      {
        title: 'Maximum Depth of Binary Tree',
        difficulty: 'Easy',
        category: 'Trees',
        url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        platform: 'LeetCode',
        topics: ['Tree', 'DFS', 'BFS'],
      },
      {
        title: 'Climbing Stairs',
        difficulty: 'Easy',
        category: '1D DP',
        url: 'https://leetcode.com/problems/climbing-stairs/',
        platform: 'LeetCode',
        topics: ['Dynamic Programming', 'Math'],
      },
      {
        title: 'Coin Change',
        difficulty: 'Medium',
        category: '1D DP',
        url: 'https://leetcode.com/problems/coin-change/',
        platform: 'LeetCode',
        topics: ['Dynamic Programming', 'BFS'],
      },
      {
        title: 'Longest Increasing Subsequence',
        difficulty: 'Medium',
        category: '1D DP',
        url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
        platform: 'LeetCode',
        topics: ['Array', 'Binary Search', 'Dynamic Programming'],
      },
      {
        title: 'Number of Islands',
        difficulty: 'Medium',
        category: 'Graphs',
        url: 'https://leetcode.com/problems/course-schedule/',
        platform: 'LeetCode',
        topics: ['DFS', 'BFS', 'Graph', 'Topological Sort'],
      },
    ]
  },
  {
    id: 'aws-devops-30',
    title: 'DevOps with AWS – 30 Day Hands-On Roadmap',
    category: 'Cloud & DevOps',
    duration: '30 Days • 4 Weeks',
    badge: 'AWS + DevOps Specialization',
    description: 'Master Cloud Engineering and DevOps from scratch in 30 days: AWS Core, Linux, Git, Terraform, Ansible, Docker, Kubernetes, and Monitoring.',
    weeks: [
      {
        weekNumber: 1,
        title: 'Week 1: AWS + Git + Linux + EC2',
        icon: '🔰',
        focus: 'AWS Account Setup, IAM, Git/GitHub, Linux CLI Mastery, EC2, Nginx',
        days: [1, 2, 3, 4, 5, 6, 7],
      },
      {
        weekNumber: 2,
        title: 'Week 2: Terraform + Ansible',
        icon: '⚙️',
        focus: 'Infrastructure as Code (IaC), S3 Remote State, Config Management, CI Automation',
        days: [8, 9, 10, 11, 12, 13, 14],
      },
      {
        weekNumber: 3,
        title: 'Week 3: S3 + Docker + ECR',
        icon: '🪣',
        focus: 'Cloud Storage Hosting, Containerization, Docker Hub, AWS ECR, EC2 Containers',
        days: [15, 16, 17, 18, 19, 20],
      },
      {
        weekNumber: 4,
        title: 'Week 4: Kubernetes + Monitoring & Delivery',
        icon: '☸️',
        focus: 'Minikube, Helm, Boto3 Python, Prometheus & Grafana, CloudWatch, EKS, Capstone',
        days: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
      },
    ],
    problems: [
      {
        day: 1,
        week: 1,
        title: 'Day 1 – AWS Account Setup',
        difficulty: 'Easy',
        category: 'AWS Core',
        platform: 'AWS Console',
        url: 'https://aws.amazon.com/resources/create-account/?p=ft&z=subnav&loc=4',
        tutorialUrl: 'https://www.youtube.com/watch?v=QDymcZ5xYow',
        topics: ['AWS', 'IAM', 'CLI', 'Security', 'MFA'],
        description: 'Create AWS Free Tier account, set up IAM user, group, and roles, configure AWS CLI, and set up billing alerts and MFA.',
        tasks: [
          'Create AWS Free Tier account',
          'Set up IAM user, group, and roles',
          'Configure AWS CLI locally',
          'Set up billing alerts and root account MFA'
        ],
      },
      {
        day: 2,
        week: 1,
        title: 'Day 2 – Git + GitHub',
        difficulty: 'Easy',
        category: 'Version Control',
        platform: 'GitHub',
        url: 'https://git-scm.com/docs',
        tutorialUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
        topics: ['Git', 'GitHub', 'Version Control', 'Pull Requests'],
        description: 'Git init, clone, add, commit, push, collaborators, create branches, merge PRs, set branch protection rules in GitHub.',
        tasks: [
          'Practice git init, clone, add, commit, push',
          'Add collaborators to repository',
          'Create feature branches, merge Pull Requests',
          'Set branch protection rules in GitHub'
        ],
      },
      {
        day: 3,
        week: 1,
        title: 'Day 3 – EC2 Setup',
        difficulty: 'Easy',
        category: 'AWS Compute',
        platform: 'AWS EC2',
        url: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EC2_GetStarted.html',
        topics: ['AWS', 'EC2', 'SSH', 'Networking'],
        description: 'Launch EC2 instance with Amazon Linux, attach key pair and security group, SSH into instance.',
        tasks: [
          'Launch EC2 instance with Amazon Linux 2023',
          'Attach key pair (.pem) and security group',
          'SSH into instance from local terminal'
        ],
      },
      {
        day: 4,
        week: 1,
        title: 'Day 4 – Linux Basics Hands-On',
        difficulty: 'Medium',
        category: 'Linux & OS',
        platform: 'Linux Terminal',
        url: 'https://linuxjourney.com/',
        topics: ['Linux', 'Bash', 'System Admin', 'Networking'],
        description: 'Master 55+ essential Linux commands for DevOps: navigation, file manipulation, permissions, process management, disk, networking, text filtering with awk, sed, and grep.',
        commands: 'ls, cd, chmod, sudo, scp, grep, curl, pwd, mkdir, touch, rm, mv, cp, cat, echo, head, tail, find, locate, chown, id, whoami, groups, ps, top, htop, kill, killall, df -h, du -sh, free -m, uptime, systemctl, journalctl, service, netstat, ss, lsof, tar, zip, unzip, rsync, wget, crontab -e, at, history, clear, awk, sed, cut, sort, uniq, tr',
        tasks: [
          'File management: ls, cd, pwd, mkdir, touch, rm, mv, cp, cat, head, tail, find',
          'Permissions & users: chmod, chown, id, whoami, groups, sudo',
          'Process & resources: ps, top, htop, kill, killall, df -h, du -sh, free -m, uptime',
          'Systemd & services: systemctl, journalctl, service',
          'Networking & transfer: netstat, ss, lsof, scp, rsync, curl, wget',
          'Text processing: awk, sed, grep, cut, sort, uniq, tr'
        ],
      },
      {
        day: 5,
        week: 1,
        title: 'Day 5 – Host Website on EC2 with Nginx',
        difficulty: 'Medium',
        category: 'Web Servers',
        platform: 'AWS EC2',
        url: 'https://docs.nginx.com/nginx/admin-guide/web-server/web-server-basics/',
        tutorialUrl: 'https://www.youtube.com/watch?v=ZWSLyqe48u4',
        topics: ['Nginx', 'EC2', 'Web Servers', 'Security Groups'],
        description: 'Install Nginx, replace default page with custom HTML, configure Nginx ports, allow HTTP/HTTPS in security group.',
        tasks: [
          'Install Nginx on EC2 instance',
          'Replace default welcome page with custom HTML',
          'Configure Nginx ports and virtual hosts',
          'Allow inbound HTTP (80) & HTTPS (443) in Security Group'
        ],
      },
      {
        day: 6,
        week: 1,
        title: 'Day 6 – Push Code to GitHub',
        difficulty: 'Easy',
        category: 'Git & Projects',
        platform: 'GitHub',
        url: 'https://github.com',
        topics: ['GitHub', 'Documentation', 'Shell Scripts'],
        description: 'Store HTML, Nginx config, and shell scripts in repository, organize repo structure, add README.md with instructions.',
        tasks: [
          'Store HTML, Nginx config, and bash scripts in git repo',
          'Organize project folder structure cleanly',
          'Add comprehensive README.md with deployment steps'
        ],
      },
      {
        day: 7,
        week: 1,
        title: 'Day 7 – Review & Practice',
        difficulty: 'Easy',
        category: 'Review & Polish',
        platform: 'DevOps Lab',
        topics: ['Review', 'Refactoring', 'Troubleshooting'],
        description: 'Review Git, EC2, Nginx setup. Fix mistakes, refactor scripts, and document learnings.',
        tasks: [
          'Review Git branching, EC2 networking, and Nginx configurations',
          'Troubleshoot and fix edge cases, refactor shell scripts',
          'Document learnings and summary notes for Week 1'
        ],
      },
      {
        day: 8,
        week: 2,
        title: 'Day 8 – Terraform Setup & CLI Commands',
        difficulty: 'Medium',
        category: 'Infrastructure as Code',
        platform: 'Terraform',
        url: 'https://developer.hashicorp.com/terraform/intro',
        topics: ['Terraform', 'IaC', 'CLI', 'DevOps'],
        description: 'Install Terraform, verify installation with terraform -version, master core Terraform commands: init, fmt, validate, plan, apply, destroy, show, output.',
        commands: 'terraform init, terraform fmt, terraform validate, terraform plan, terraform apply, terraform destroy, terraform show, terraform output',
        tasks: [
          'Install Terraform CLI locally and verify installation',
          'terraform init – initialize project and download providers',
          'terraform fmt & validate – format code and verify syntax',
          'terraform plan & apply – preview and create cloud resources',
          'terraform show & output – inspect state and display values',
          'terraform destroy – clean up provisioned resources'
        ],
      },
      {
        day: 9,
        week: 2,
        title: 'Day 9 – EC2 Instance + Security Group with Terraform',
        difficulty: 'Medium',
        category: 'Terraform & AWS',
        platform: 'Terraform',
        url: 'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance',
        topics: ['Terraform', 'AWS EC2', 'HCL', 'User Data'],
        description: 'Initialize a Terraform project to provision an EC2 instance. Create security group for SSH (22) and HTTP (80). Use variables for region, AMI, instance type. Add user_data for Nginx. Add output block for public IP.',
        tasks: [
          'Initialize Terraform project with AWS provider',
          'Create security group allowing SSH (port 22) and HTTP (port 80)',
          'Define variables for AWS region, AMI ID, instance type, key pair',
          'Add user_data script to auto-install Nginx on launch',
          'Add output block to print EC2 public IP after apply'
        ],
      },
      {
        day: 10,
        week: 2,
        title: 'Day 10 – Remote Backend with S3 + DynamoDB',
        difficulty: 'Hard',
        category: 'Terraform State',
        platform: 'AWS S3 & DynamoDB',
        url: 'https://developer.hashicorp.com/terraform/language/settings/backends/s3',
        topics: ['Terraform', 'AWS S3', 'DynamoDB', 'State Locking'],
        description: 'Configure remote backend to store the Terraform state file in an S3 bucket with state locking via DynamoDB table. Update provider.tf and re-run terraform init.',
        tasks: [
          'Create S3 bucket with encryption for remote tfstate storage',
          'Create DynamoDB table with LockID partition key for state locking',
          'Update backend block in provider.tf to reference S3 and DynamoDB',
          'Re-run terraform init to migrate local state to remote backend'
        ],
      },
      {
        day: 11,
        week: 2,
        title: 'Day 11 – Ansible Setup for EC2',
        difficulty: 'Medium',
        category: 'Configuration Management',
        platform: 'Ansible',
        url: 'https://docs.ansible.com/ansible/latest/getting_started/index.html',
        topics: ['Ansible', 'Configuration Management', 'YAML', 'Nginx'],
        description: 'Install Ansible on your local machine. Create an inventory file with EC2 IP. Write an Ansible playbook to install Nginx, copy HTML files, and start the service.',
        tasks: [
          'Install Ansible CLI on local machine',
          'Create inventory.ini file with EC2 public IP and SSH key',
          'Write Ansible playbook (playbook.yml) with tasks',
          'Automate Nginx install, HTML copy, and service start with Ansible'
        ],
      },
      {
        day: 12,
        week: 2,
        title: 'Day 12 – Combine Terraform + Ansible',
        difficulty: 'Hard',
        category: 'End-to-End IaC',
        platform: 'Terraform & Ansible',
        url: 'https://learn.hashicorp.com/tutorials/terraform/ansible-provider',
        topics: ['Terraform', 'Ansible', 'CI/CD', 'Automation'],
        description: 'Provision EC2 with Terraform, configure Nginx with Ansible using Terraform output IP dynamically.',
        tasks: [
          'Provision infrastructure via Terraform apply',
          'Dynamically generate Ansible inventory from terraform output IP',
          'Execute Ansible playbook against newly provisioned instance',
          'Verify website availability via public IP'
        ],
      },
      {
        day: 13,
        week: 2,
        title: 'Day 13 – Push Project to GitHub',
        difficulty: 'Easy',
        category: 'Git & Best Practices',
        platform: 'GitHub',
        url: 'https://github.com',
        topics: ['Git', 'Project Structure', 'Best Practices'],
        description: 'Separate terraform/ and ansible/ directories. Add README.md and .gitignore to exclude sensitive keys and tfstate.',
        tasks: [
          'Organize project with distinct terraform/ and ansible/ directories',
          'Add .gitignore for .terraform/, *.tfstate, and private keys',
          'Write step-by-step documentation in README.md and push to GitHub'
        ],
      },
      {
        day: 14,
        week: 2,
        title: 'Day 14 – Automation with Shell Script',
        difficulty: 'Medium',
        category: 'Bash & Automation',
        platform: 'Bash Shell',
        topics: ['Bash', 'Shell Scripting', 'End-to-End Automation'],
        description: 'Create a shell script to run Terraform apply, wait for EC2 to pass health checks, and run Ansible playbook automatically.',
        tasks: [
          'Write deploy.sh orchestrator script',
          'Automate terraform apply -auto-approve execution',
          'Implement polling loop to wait for EC2 SSH port availability',
          'Trigger ansible-playbook execution automatically'
        ],
      },
      {
        day: 15,
        week: 3,
        title: 'Day 15 – S3 Hands-On with Terraform',
        difficulty: 'Medium',
        category: 'AWS Storage',
        platform: 'AWS S3 & Terraform',
        url: 'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket',
        topics: ['AWS S3', 'Terraform', 'Static Hosting', 'Cloud Storage'],
        description: 'Create S3 bucket with Terraform, enable bucket versioning, configure bucket for static website hosting.',
        tasks: [
          'Write Terraform code for S3 bucket creation',
          'Enable bucket versioning resource',
          'Configure S3 static website hosting and error documents',
          'Configure bucket policy for public read access'
        ],
      },
      {
        day: 16,
        week: 3,
        title: 'Day 16 – Host Website on S3 via Ansible',
        difficulty: 'Medium',
        category: 'Cloud Automation',
        platform: 'Ansible & AWS S3',
        topics: ['Ansible', 'AWS S3', 'Web Hosting'],
        description: 'Use Ansible to sync local HTML files to S3, set permissions for public access, and access site via S3 website endpoint.',
        tasks: [
          'Install amazon.aws Ansible collection and boto3',
          'Write playbook to synchronize static assets to S3 bucket',
          'Apply appropriate S3 object ACLs and MIME types',
          'Access and test website via S3 website endpoint URL'
        ],
      },
      {
        day: 17,
        week: 3,
        title: 'Day 17 – Docker Basics',
        difficulty: 'Medium',
        category: 'Containerization',
        platform: 'Docker',
        url: 'https://docs.docker.com/get-started/',
        topics: ['Docker', 'Containers', 'Dockerfile', 'Nginx'],
        description: 'Install Docker, learn docker build, run, images, ps. Create Dockerfile for custom Nginx + HTML website.',
        commands: 'docker build, docker run -d -p 80:80, docker images, docker ps, docker stop, docker rm',
        tasks: [
          'Install Docker Engine / Docker Desktop',
          'Master CLI commands: docker build, run, ps, images, exec, logs',
          'Write custom Dockerfile with multi-stage / Nginx base',
          'Build image and run container with port forwarding (80:80)'
        ],
      },
      {
        day: 18,
        week: 3,
        title: 'Day 18 – Push Docker Image to Docker Hub',
        difficulty: 'Easy',
        category: 'Container Registries',
        platform: 'Docker Hub',
        url: 'https://hub.docker.com',
        topics: ['Docker Hub', 'Container Registry', 'Image Tagging'],
        description: 'Create Docker Hub account, tag image and push to repo, pull from another system and test.',
        tasks: [
          'Create Docker Hub account and login via docker login',
          'Tag local image with username/repo:tag format',
          'Push image to Docker Hub repository',
          'Pull image on remote system / VM and run container'
        ],
      },
      {
        day: 19,
        week: 3,
        title: 'Day 19 – Push Docker Image to AWS ECR',
        difficulty: 'Medium',
        category: 'AWS Containers',
        platform: 'AWS ECR',
        url: 'https://docs.aws.amazon.com/AmazonECR/latest/userguide/what-is-ecr.html',
        topics: ['AWS ECR', 'Docker', 'AWS CLI', 'Security'],
        description: 'Create ECR repo using console or Terraform. Authenticate using AWS CLI (`aws ecr get-login-password`). Push Docker image to ECR.',
        tasks: [
          'Create AWS ECR repository via CLI or Terraform',
          'Authenticate Docker client to ECR registry using AWS CLI',
          'Tag Docker image with ECR repository URI',
          'Push container image to private AWS ECR repository'
        ],
      },
      {
        day: 20,
        week: 3,
        title: 'Day 20 – Run Image on EC2 using Docker',
        difficulty: 'Medium',
        category: 'AWS Compute & Containers',
        platform: 'AWS EC2 & Docker',
        topics: ['AWS EC2', 'Docker', 'AWS ECR', 'Container Deployment'],
        description: 'Install Docker on EC2, pull image from ECR, run container and expose port to test.',
        tasks: [
          'Install and start Docker daemon on EC2 instance',
          'Attach IAM role to EC2 with ECR read permissions',
          'Pull custom Docker image from AWS ECR repository',
          'Run container with -p 80:80 and verify via EC2 public IP'
        ],
      },
      {
        day: 21,
        week: 4,
        title: 'Day 21 – Kubernetes with Minikube',
        difficulty: 'Medium',
        category: 'Kubernetes',
        platform: 'Minikube & kubectl',
        url: 'https://minikube.sigs.k8s.io/docs/start/',
        topics: ['Kubernetes', 'Minikube', 'kubectl', 'Pods', 'Services'],
        description: 'Install Minikube + kubectl, start local cluster, deploy simple Nginx pod and service.',
        commands: 'minikube start, kubectl get nodes, kubectl run, kubectl get pods, kubectl expose, kubectl logs',
        tasks: [
          'Install Minikube and kubectl CLI locally',
          'Start single-node Kubernetes cluster with minikube start',
          'Deploy simple Nginx pod with kubectl run',
          'Expose pod as NodePort / ClusterIP service and verify'
        ],
      },
      {
        day: 22,
        week: 4,
        title: 'Day 22 – App Deployment in Minikube',
        difficulty: 'Medium',
        category: 'Kubernetes Manifests',
        platform: 'Kubernetes',
        url: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/',
        topics: ['Kubernetes', 'Deployments', 'Services', 'YAML'],
        description: 'Deploy your Docker image on Minikube. Use Deployment + Service YAML manifests. Access using minikube service.',
        tasks: [
          'Write deployment.yaml with replicas, labels, and container spec',
          'Write service.yaml with NodePort configuration',
          'Apply manifests using kubectl apply -f',
          'Access running application via minikube service command'
        ],
      },
      {
        day: 23,
        week: 4,
        title: 'Day 23 – Helm Basics',
        difficulty: 'Hard',
        category: 'Kubernetes Packaging',
        platform: 'Helm',
        url: 'https://helm.sh/docs/intro/quickstart/',
        topics: ['Helm', 'Kubernetes', 'Package Management', 'Charts'],
        description: 'Install Helm, use Helm to deploy Nginx, learn values.yaml, release lifecycle, upgrade, package your own Helm chart.',
        commands: 'helm repo add, helm install, helm list, helm upgrade, helm create, helm package',
        tasks: [
          'Install Helm package manager',
          'Add Bitnami repo and deploy Nginx chart',
          'Learn values.yaml customization, release upgrade & rollback',
          'Create and package custom Helm chart using helm create'
        ],
      },
      {
        day: 24,
        week: 4,
        title: 'Day 24 – Python Scripting for AWS',
        difficulty: 'Medium',
        category: 'Cloud Automation & SDKs',
        platform: 'Python & Boto3',
        url: 'https://boto3.amazonaws.com/v1/documentation/api/latest/index.html',
        topics: ['Python', 'Boto3', 'AWS SDK', 'Cloud Automation'],
        description: 'Install Boto3 in Python. Write scripts to: List EC2 instances, find unused EBS volumes, and upload file to S3.',
        tasks: [
          'Install boto3 SDK and configure AWS credentials',
          'Write script to list all running and stopped EC2 instances',
          'Write script to inspect and flag unused detached EBS volumes',
          'Write script to upload automated backup files to S3 bucket'
        ],
      },
      {
        day: 25,
        week: 4,
        title: 'Day 25 – Automate with Cron',
        difficulty: 'Easy',
        category: 'Automation & Cron',
        platform: 'Linux Cron',
        topics: ['Cron', 'Linux', 'Automation', 'Logging'],
        description: 'Write a shell script to run your Python script, schedule with cron, log output to file.',
        tasks: [
          'Create wrapper shell script for Python virtualenv execution',
          'Configure crontab entry (crontab -e) for recurring schedule',
          'Redirect stdout and stderr to timestamped log files',
          'Verify execution logs and error handling'
        ],
      },
      {
        day: 26,
        week: 4,
        title: 'Day 26 – Monitoring: Prometheus + Grafana on Minikube',
        difficulty: 'Hard',
        category: 'Observability',
        platform: 'Prometheus & Grafana',
        url: 'https://prometheus-community.github.io/helm-charts/',
        topics: ['Prometheus', 'Grafana', 'Observability', 'Helm', 'K8s'],
        description: 'Install Prometheus & Grafana via Helm, access dashboards, monitor pod CPU/memory.',
        tasks: [
          'Deploy kube-prometheus-stack chart on Minikube via Helm',
          'Port-forward and access Grafana web dashboard',
          'Configure Kubernetes cluster monitoring dashboards',
          'Inspect pod CPU, memory usage metrics, and query PromQL'
        ],
      },
      {
        day: 27,
        week: 4,
        title: 'Day 27 – CloudWatch Logs + Alarms (for EC2)',
        difficulty: 'Medium',
        category: 'AWS Monitoring',
        platform: 'AWS CloudWatch',
        url: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html',
        topics: ['AWS CloudWatch', 'Monitoring', 'Alarms', 'EC2'],
        description: 'Install CloudWatch agent on EC2, send logs and metrics, create CPU usage alarm.',
        tasks: [
          'Install Amazon CloudWatch unified agent on EC2 instance',
          'Configure amazon-cloudwatch-agent.json to collect system logs',
          'Verify metrics in AWS CloudWatch Console',
          'Create CloudWatch Alarm for high CPU utilization (>80%) with SNS notification'
        ],
      },
      {
        day: 28,
        week: 4,
        title: 'Day 28 – Optional EKS Hands-On (Advanced)',
        difficulty: 'Hard',
        category: 'Managed Kubernetes',
        platform: 'AWS EKS',
        url: 'https://eksctl.io/introduction/',
        topics: ['AWS EKS', 'eksctl', 'Kubernetes', 'Enterprise Cloud'],
        description: 'Install eksctl and kubectl. Create EKS cluster with 1-node group. Deploy Helm chart on EKS. Clean up resources post usage.',
        tasks: [
          'Install eksctl CLI tool',
          'Provision managed EKS cluster with 1-node managed group',
          'Configure kubeconfig and deploy application Helm chart on EKS',
          'Tear down EKS cluster using eksctl delete cluster to avoid AWS costs'
        ],
      },
      {
        day: 29,
        week: 4,
        title: 'Day 29 – Final Project Prep',
        difficulty: 'Hard',
        category: 'Capstone Architecture',
        platform: 'Full DevOps Stack',
        topics: ['Capstone Project', 'Full Stack DevOps', 'Architecture'],
        description: 'Assemble your capstone project combining: Terraform (infra) + Ansible (app setup) + Docker (custom image) + Kubernetes (Minikube deployment) + Monitoring (Grafana).',
        tasks: [
          'Review Terraform infra scripts for VPC, EC2, and S3 backend',
          'Verify Ansible playbooks for server bootstrapping',
          'Audit Docker container multi-stage build optimization',
          'Test Kubernetes Deployment, Service, and Ingress resources',
          'Verify Prometheus metrics scrapers and Grafana dashboard layout'
        ],
      },
      {
        day: 30,
        week: 4,
        title: 'Day 30 – Final Project Delivery',
        difficulty: 'Medium',
        category: 'Portfolio & Delivery',
        platform: 'GitHub & LinkedIn',
        url: 'https://linkedin.com',
        topics: ['Portfolio', 'GitHub', 'LinkedIn', 'Documentation'],
        description: 'Push all code to GitHub. Structure repo with README, folders. Record a video walkthrough (optional). Share with mentors/LinkedIn.',
        tasks: [
          'Push complete production code to GitHub public repository',
          'Create professional README with architecture diagram and setup guide',
          'Record short video walkthrough demonstrating live deployment',
          'Publish achievement post with project summary on LinkedIn'
        ],
      },
    ]
  }
];

